name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dart-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: '3.5.3'
    
    - name: Change dir to tests/dart
      run: cd tests/dart

    - name: Install dependencies
      run: dart pub get

    - name: Run tests
      run: dart test
